### PR TITLE
nixos: set correct $PATH

### PR DESCRIPTION
**Pull request by domenkozar**
Not yet tested.

### CODE REVIEW

**Comment by roberth** [comment]
This doesn't really do much because it is only active when `useSystemd` is active and the init script + systemd manage `$PATH` themselves.
So this should only have any effect when overriding the image or service command to do something *very* different, which seems like a bad idea, particularly because the meaning of `useSystemd` is now contradicted and because systemd requires some special treatment that should not be applied to typical processes, like the weird shutdown signal.
So when overriding a NixOS image to something simpler, we should recommend `useSystemd = lib.mkForce false` and perhaps #42 is the answer to the underlying question... :D

**Comment by domenkozar** [comment]
I should have written motivation for the change.

When using NixOS module and `docker exec`, there are no binaries available because default `$PATH` only contains FHS paths that Nix doesn't have.

So you can't even do `docker exec container -ti ls` because it won't find coreutils.

**Comment by roberth** [comment]
Ah yes. I sort of solved this in `arion exec` but that's doesn't solve the problem outside `arion`. I don't think we can ask every tool to call into arion instead of docker, so yeah, we should probably do this. `arion exec` is a bit more powerful, so we should document the difference.

**Comment by roberth** [comment]
Not calling you a tool; was thinking about the docker ecosystem :rofl:

**Comment by domenkozar** [comment]
@roberth let's merge this one?

**Pull request merged**
