### PR TITLE
Add service.labels

### LINKED ISSUE #107: Container label support
As far as I can see from reading the docs, there is currently no way to specify [docker container labels](docker-compose.raw
) in an `arion-compose.nix` file. Labels can be useful as some containers - most notably 
[traefik](https://doc.traefik.io/traefik/providers/docker/#routing-configuration-with-labels) - can be configured via labels. Can label support be added via e.g. `services.<name>.service.labels`?

### PR DESCRIPTION
**Pull request by roberth**
- [x] add traefik example
 - [x] test the example
 - [x] replace the module option example with something better

@lunik1 could you provide an example project with traefik?

Closes #107

### CODE REVIEW

**Comment by lunik1** [comment]
@roberth Yes. To clarify you mean an example `arion-compose.nix`? I think translating [this example from the traefik docs](https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/) makes the most sense?

**Comment by roberth** [comment]
> you mean an example `arion-compose.nix`?

Yes. I think this would make a valuable example.

**Comment by lunik1** [comment]
```nix
{ pkgs, ... }: {

  config.services = {
    traefik.service = {
      image = "traefik:v2.4";
      container_name = "traefik";
      command = [
        "--api.insecure=true"
        "--providers.docker=true"
        "--providers.docker.exposedbydefault=false"
        "--entrypoints.web.address=:80"
      ];
      ports = [ "80:80" "8080:8080" ];
      volumes = [ "/var/run/docker.sock:/var/run/docker.sock:ro" ];
    };

    whoami.service = {
      image = "traefik/whoami";
      container_name = "simple-service";
      labels = {
        "traefik.enable" = "true";
        "traefik.http.routers.whoami.rule" = "Host(`whoami.localhost`)";
        "traefik.http.routers.whoami.entrypoints" = "web";
      };
    };
  };
}
```

This is the equivalent of the example given in the traefik documentation. It has traefik working as a reverse proxy to the `whoami` container, available at `http://whoami.localhost`. This is achieved by setting the appropriate labels on the `whoami` container.

**Comment by roberth** [comment]
Thanks for the input!

**Comment by lunik1** [comment]
No problem, thanks for implementing this so quickly!

**Pull request merged**
